<a href="https://colab.research.google.com/github/oishikbanik/Ai_lab_task/blob/main/lab_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [ ]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [ ]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.6552, 0.1639],
        [0.0903, 0.7564]])

In [ ]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.7233, 0.3868, 0.4336],
        [0.3119, 0.0714, 0.6592]])

In [ ]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
rand_tensor.dtype

torch.float32

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [ ]:
rand_tensor

tensor([[0.7233, 0.3868, 0.4336],
        [0.3119, 0.0714, 0.6592]])

In [ ]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.7233, 1.0000, 0.4336],
        [0.3119, 1.0000, 0.6592]])

In [ ]:
rand_tensor[0]

tensor([0.7233, 1.0000, 0.4336])

In [ ]:
rand_tensor[:,0]

tensor([0.7233, 0.3119])

In [ ]:
rand_tensor[...,-1]

tensor([0.4336, 0.6592])

In [ ]:
rand_tensor.sum()

tensor(4.1280)

In [ ]:
rand_tensor.sum().item()

4.128016948699951

In [ ]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.7233, 1.0000, 0.4336, 0.0000, 0.0000, 0.0000],
        [0.3119, 1.0000, 0.6592, 0.0000, 0.0000, 0.0000]])

In [ ]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.7233, 1.0000, 0.4336],
        [0.3119, 1.0000, 0.6592],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [ ]:
rand_tensor.mul(ones_tensor)

tensor([[0.7233, 1.0000, 0.4336],
        [0.3119, 1.0000, 0.6592]])

In [ ]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.7112, 1.5114],
        [1.5114, 1.5318]])

In [ ]:
rand_tensor.add_(5)

tensor([[5.7233, 6.0000, 5.4336],
        [5.3119, 6.0000, 5.6592]])

In [ ]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [ ]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [ ]:
x = torch.empty(1)
print(x)

tensor([-29.3893])


In [ ]:
x.size()

torch.Size([1])

In [ ]:
x = torch.empty(2,3)
print(x)

tensor([[-2.9389e+01,  4.5147e-41, -2.9389e+01],
        [ 4.5147e-41, -2.9321e-09,  4.5147e-41]])


In [ ]:
torch.empty(2,2,3)

tensor([[[-2.9389e+01,  4.5147e-41, -2.9389e+01],
         [ 4.5147e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00,  4.4537e+32],
         [ 3.1985e-41,  1.8077e-43,  0.0000e+00]]])

In [ ]:
y=x.view(6)
y

tensor([-2.9389e+01,  4.5147e-41, -8.7810e+26,  3.1989e-41,  4.4842e-44,
         0.0000e+00])

In [ ]:
z=x.view(1,-1)
z

tensor([[-2.9389e+01,  4.5147e-41, -2.9389e+01,  4.5147e-41, -2.9321e-09,
          4.5147e-41]])

In [ ]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [ ]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [ ]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
a[1,1].item()

1.0

In [ ]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])